# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.2
_src_path: https://github.com/jupyterlab/extension-template
author_email: bmharris626@gmail.com
author_name: jupyterhub-wikilab
create_claude_symlink: false
create_gemini_symlink: false
has_ai_rules: true
has_binder: false
has_settings: false
kind: frontend-and-server
labextension_name: jupyterhub-wikilab
project_short_description: An extension for displaying/editing wikis within jupyterhub
    workspace
python_name: jupyterhub_wikilab
repository: https://github.com/bmharris626/jupyter-wikilab
test: true

